version: '3'
services:
  app:
    container_name: wager_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - api:/usr/src/app/
    depends_on:
      - wager-mysql
    networks:
      - wagernetwork


  wager-mysql:
    image: mysql:5.7
    container_name: wager_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - wagernetwork

volumes:
  api:
  database_mysql:

networks:
  wagernetwork:
    driver: bridge

